'use client';

import { useState, use } from 'react';
import Link from 'next/link';
import countriesData from '@/data/countries.json';
import { calculateTax, Country } from '@/lib/taxCalculator';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, BarChart, Bar, XAxis, YAxis, CartesianGrid } from 'recharts';
import jsPDF from 'jspdf';

const COLORS = ['#10b981', '#ef4444', '#f59e0b'];

export default function CountryPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = use(params);
  const country = countriesData.find((c) => c.id === slug) as Country;

  const [salary, setSalary] = useState(60000);

  if (!country) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white">
        <div className="text-center">
          <h1 className="text-4xl font-bold mb-4 text-gray-900">Country Not Found</h1>
          <Link href="/" className="text-gray-600 hover:text-gray-900 underline">
            Back to Home
          </Link>
        </div>
      </div>
    );
  }

  const calculation = calculateTax(salary, country);

  const pieData = [
    { name: 'Net Salary', value: calculation.netSalary },
    { name: 'Income Tax', value: calculation.incomeTax },
    { name: 'Social Security', value: calculation.socialSecurity },
  ];

  const monthlyData = [
    { name: 'Monthly Net', value: calculation.monthlyNet },
    { name: 'Cost of Living', value: calculation.monthlyCostOfLiving },
    { name: 'Disposable', value: calculation.monthlyDisposable },
  ];

  const downloadPDF = () => {
    const doc = new jsPDF();
    
    doc.setFontSize(20);
    doc.text(`Tax Report: ${country.name}`, 20, 20);
    
    doc.setFontSize(12);
    doc.text(`Annual Gross Salary: ${country.currency_symbol}${salary.toLocaleString()}`, 20, 40);
    doc.text(`Income Tax: ${country.currency_symbol}${calculation.incomeTax.toLocaleString()}`, 20, 50);
    doc.text(`Social Security: ${country.currency_symbol}${calculation.socialSecurity.toLocaleString()}`, 20, 60);
    doc.text(`Total Tax: ${country.currency_symbol}${calculation.totalTax.toLocaleString()}`, 20, 70);
    doc.text(`Net Salary: ${country.currency_symbol}${calculation.netSalary.toLocaleString()}`, 20, 80);
    doc.text(`Effective Tax Rate: ${calculation.effectiveTaxRate}%`, 20, 90);
    
    doc.text(`Monthly Net Income: ${country.currency_symbol}${calculation.monthlyNet.toLocaleString()}`, 20, 110);
    doc.text(`Monthly Cost of Living: ${country.currency_symbol}${calculation.monthlyCostOfLiving.toLocaleString()}`, 20, 120);
    doc.text(`Monthly Disposable Income: ${country.currency_symbol}${calculation.monthlyDisposable.toLocaleString()}`, 20, 130);
    
    doc.setFontSize(10);
    doc.text('Generated by RemoteTaxHub.com', 20, 150);
    doc.text('Disclaimer: This is an estimate. Consult a tax professional.', 20, 160);
    
    doc.save(`${country.name}-tax-report.pdf`);
  };

  return (
    <div className="min-h-screen bg-zinc-50">
      {/* Navigation */}
      <nav className="fixed top-0 w-full bg-white/80 backdrop-blur-md border-b border-zinc-200 z-50">
        <div className="max-w-6xl mx-auto px-6">
          <div className="flex justify-between items-center h-16">
            <Link href="/" className="font-bold text-lg">
              Remote<span className="text-blue-600">Tax</span>Hub
            </Link>
            <Link href="/compare" className="text-sm px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">
              Compare
            </Link>
          </div>
        </div>
      </nav>

      {/* Header */}
      <div className="pt-24 pb-12 px-6 bg-zinc-50 border-b border-zinc-200">
        <div className="max-w-6xl mx-auto">
          <Link href="/" className="inline-flex items-center gap-1 text-sm text-zinc-600 hover:text-zinc-900 mb-6">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Back
          </Link>
          <h1 className="text-4xl font-bold text-zinc-900 mb-3">{country.name}</h1>
          <p className="text-lg text-zinc-600">{country.description}</p>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-6 py-12">
        {/* Salary Input */}
        <div className="bg-white border border-zinc-200 rounded-xl p-8 mb-8">
          <h2 className="text-2xl font-bold mb-8 text-zinc-900">Your Take-Home Pay</h2>
          
          <div className="mb-8">
            <label className="block text-sm font-semibold text-zinc-900 mb-4">
              Annual Salary ({country.currency_symbol})
            </label>
            <input
              type="range"
              min="10000"
              max="200000"
              step="5000"
              value={salary}
              onChange={(e) => setSalary(Number(e.target.value))}
              className="w-full h-2 bg-zinc-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
            />
            <div className="flex justify-between mt-4">
              <span className="text-sm text-zinc-500">{country.currency_symbol}10,000</span>
              <span className="text-3xl font-bold text-zinc-900">
                {country.currency_symbol}{salary.toLocaleString()}
              </span>
              <span className="text-sm text-zinc-500">{country.currency_symbol}200,000</span>
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-4">
            <input
              type="number"
              value={salary}
              onChange={(e) => setSalary(Number(e.target.value))}
              className="border border-zinc-300 rounded-lg px-4 py-3 text-lg focus:border-blue-600 focus:ring-1 focus:ring-blue-600 outline-none"
              placeholder="Custom amount"
            />
            <button
              onClick={downloadPDF}
              className="bg-blue-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-blue-700 transition-colors flex items-center justify-center gap-2"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Download PDF
            </button>
          </div>
        </div>

        {/* Results Grid */}
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          <div className="bg-gray-50 border border-gray-200 rounded-xl p-6">
            <div className="text-sm text-gray-600 mb-2 font-medium">Gross Salary</div>
            <div className="text-4xl font-bold text-gray-900 mb-1">
              {country.currency_symbol}{calculation.grossSalary.toLocaleString()}
            </div>
            <div className="text-sm text-gray-500">Annual income</div>
          </div>
          
          <div className="bg-red-50 border border-red-200 rounded-xl p-6">
            <div className="text-sm text-red-700 mb-2 font-medium">Total Tax</div>
            <div className="text-4xl font-bold text-red-600 mb-1">
              -{country.currency_symbol}{calculation.totalTax.toLocaleString()}
            </div>
            <div className="text-sm text-red-600">
              {calculation.effectiveTaxRate}% effective rate
            </div>
          </div>
          
          <div className="bg-green-50 border border-green-200 rounded-xl p-6">
            <div className="text-sm text-green-700 mb-2 font-medium">Net Salary</div>
            <div className="text-4xl font-bold text-green-600 mb-1">
              {country.currency_symbol}{calculation.netSalary.toLocaleString()}
            </div>
            <div className="text-sm text-green-600">
              {country.currency_symbol}{calculation.monthlyNet.toLocaleString()}/month
            </div>
          </div>
        </div>

        {/* Tax Breakdown */}
        <div className="grid md:grid-cols-2 gap-8 mb-8">
          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h3 className="text-xl font-bold mb-6 text-gray-900">Tax Breakdown</h3>
            <div className="space-y-4 mb-6">
              <div className="flex justify-between items-center pb-3 border-b border-gray-100">
                <span className="text-gray-600">Income Tax</span>
                <span className="font-semibold text-gray-900">
                  {country.currency_symbol}{calculation.incomeTax.toLocaleString()}
                </span>
              </div>
              <div className="flex justify-between items-center pb-3 border-b border-gray-100">
                <span className="text-gray-600">Social Security</span>
                <span className="font-semibold text-gray-900">
                  {country.currency_symbol}{calculation.socialSecurity.toLocaleString()}
                </span>
              </div>
              <div className="flex justify-between items-center pt-2">
                <span className="font-semibold text-gray-900">Total Deductions</span>
                <span className="font-bold text-gray-900">
                  {country.currency_symbol}{calculation.totalTax.toLocaleString()}
                </span>
              </div>
            </div>
            
            <div className="h-64">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={pieData}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    label={({ name, percent }) => `${name} ${((percent || 0) * 100).toFixed(0)}%`}
                    outerRadius={80}
                    fill="#8884d8"
                    dataKey="value"
                  >
                    {pieData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip formatter={(value) => `${country.currency_symbol}${Number(value || 0).toLocaleString()}`} />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h3 className="text-xl font-bold mb-6 text-gray-900">Monthly Budget</h3>
            <div className="space-y-4 mb-6">
              <div className="flex justify-between items-center pb-3 border-b border-gray-100">
                <span className="text-gray-600">Monthly Net Income</span>
                <span className="font-semibold text-gray-900">
                  {country.currency_symbol}{calculation.monthlyNet.toLocaleString()}
                </span>
              </div>
              <div className="flex justify-between items-center pb-3 border-b border-gray-100">
                <span className="text-gray-600">Cost of Living</span>
                <span className="font-semibold text-gray-900">
                  {country.currency_symbol}{calculation.monthlyCostOfLiving.toLocaleString()}
                </span>
              </div>
              <div className="flex justify-between items-center pt-2">
                <span className="font-semibold text-gray-900">Disposable Income</span>
                <span className={`font-bold ${calculation.monthlyDisposable > 0 ? 'text-green-600' : 'text-red-600'}`}>
                  {country.currency_symbol}{calculation.monthlyDisposable.toLocaleString()}
                </span>
              </div>
            </div>

            <div className="h-64">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={monthlyData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                  <XAxis dataKey="name" tick={{ fontSize: 12 }} />
                  <YAxis tick={{ fontSize: 12 }} />
                  <Tooltip formatter={(value) => `${country.currency_symbol}${Number(value || 0).toLocaleString()}`} />
                  <Bar dataKey="value" fill="#111827" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>

        {/* Tax Brackets Table */}
        <div className="bg-white border border-gray-200 rounded-xl p-6 mb-8">
          <h3 className="text-xl font-bold mb-6 text-gray-900">Tax Brackets in {country.name}</h3>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-gray-200">
                  <th className="text-left py-3 px-4 text-sm font-semibold text-gray-900">Income Range</th>
                  <th className="text-right py-3 px-4 text-sm font-semibold text-gray-900">Tax Rate</th>
                </tr>
              </thead>
              <tbody>
                {country.tax_brackets.map((bracket, index) => (
                  <tr key={index} className="border-b border-gray-100 hover:bg-gray-50">
                    <td className="py-3 px-4 text-sm text-gray-600">
                      {country.currency_symbol}{bracket.min.toLocaleString()} - {' '}
                      {bracket.max === 999999999 
                        ? '∞' 
                        : `${country.currency_symbol}${bracket.max.toLocaleString()}`}
                    </td>
                    <td className="text-right py-3 px-4 font-semibold text-gray-900 text-sm">
                      {bracket.rate}%
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="mt-4 text-sm text-gray-600">
            Social Security Rate: <span className="font-semibold text-gray-900">{country.social_security}%</span>
          </div>
        </div>

        {/* Compare CTA */}
        <div className="bg-gray-900 text-white rounded-xl p-10 text-center">
          <h2 className="text-2xl font-bold mb-3">
            Want to compare with other countries?
          </h2>
          <p className="text-gray-400 mb-6">
            See how {country.name} stacks up against other destinations
          </p>
          <Link
            href="/compare"
            className="inline-block px-6 py-3 bg-white text-gray-900 font-semibold rounded-lg hover:bg-gray-100 transition-colors"
          >
            Compare Countries
          </Link>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-50 border-t border-gray-200 py-12 mt-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-sm text-gray-600">
          <p>© 2026 RemoteTaxHub. Tax calculations are estimates. Consult a tax professional for accurate advice.</p>
        </div>
      </footer>
    </div>
  );
}
