'use client';

import { useState, use } from 'react';
import Link from 'next/link';
import countriesData from '@/data/countries.json';
import { calculateTax, Country } from '@/lib/taxCalculator';
import { getTranslation } from '@/lib/translations';
import LanguageSwitcher from '@/components/LanguageSwitcher';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, BarChart, Bar, XAxis, YAxis, CartesianGrid } from 'recharts';
import jsPDF from 'jspdf';

const COLORS = ['#10b981', '#ef4444', '#f59e0b'];

export default function CountryPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = use(params);
  const country = countriesData.find((c) => c.id === slug) as Country;

  const [salary, setSalary] = useState(60000);
  const [currentLang, setCurrentLang] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('language') || 'en';
    }
    return 'en';
  });

  const handleLanguageChange = (lang: string) => {
    setCurrentLang(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = getTranslation(currentLang);

  if (!country) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white">
        <div className="text-center">
          <h1 className="text-4xl font-bold mb-4 text-zinc-900">{t.countryNotFound}</h1>
          <Link href="/" className="text-zinc-600 hover:text-zinc-900 underline">
            {t.backToHome}
          </Link>
        </div>
      </div>
    );
  }

  const calculation = calculateTax(salary, country);

  const pieData = [
    { name: 'Net Salary', value: calculation.netSalary },
    { name: 'Income Tax', value: calculation.incomeTax },
    { name: 'Social Security', value: calculation.socialSecurity },
  ];

  const monthlyData = [
    { name: 'Monthly Net', value: calculation.monthlyNet },
    { name: 'Cost of Living', value: calculation.monthlyCostOfLiving },
    { name: 'Disposable', value: calculation.monthlyDisposable },
  ];

  const downloadPDF = () => {
    const doc = new jsPDF();
    
    doc.setFontSize(20);
    doc.text(`Tax Report: ${country.name}`, 20, 20);
    
    doc.setFontSize(12);
    doc.text(`Annual Gross Salary: ${country.currency_symbol}${salary.toLocaleString()}`, 20, 40);
    doc.text(`Income Tax: ${country.currency_symbol}${calculation.incomeTax.toLocaleString()}`, 20, 50);
    doc.text(`Social Security: ${country.currency_symbol}${calculation.socialSecurity.toLocaleString()}`, 20, 60);
    doc.text(`Total Tax: ${country.currency_symbol}${calculation.totalTax.toLocaleString()}`, 20, 70);
    doc.text(`Net Salary: ${country.currency_symbol}${calculation.netSalary.toLocaleString()}`, 20, 80);
    doc.text(`Effective Tax Rate: ${calculation.effectiveTaxRate}%`, 20, 90);
    
    doc.text(`Monthly Net Income: ${country.currency_symbol}${calculation.monthlyNet.toLocaleString()}`, 20, 110);
    doc.text(`Monthly Cost of Living: ${country.currency_symbol}${calculation.monthlyCostOfLiving.toLocaleString()}`, 20, 120);
    doc.text(`Monthly Disposable Income: ${country.currency_symbol}${calculation.monthlyDisposable.toLocaleString()}`, 20, 130);
    
    doc.setFontSize(10);
    doc.text('Generated by RemoteTaxHub.com', 20, 150);
    doc.text('Disclaimer: This is an estimate. Consult a tax professional.', 20, 160);
    
    doc.save(`${country.name}-tax-report.pdf`);
  };

  return (
    <div className="min-h-screen bg-zinc-50">
      {/* Navigation */}
      <nav className="fixed top-0 w-full bg-white/95 backdrop-blur-sm border-b border-zinc-200 z-50">
        <div className="max-w-6xl mx-auto px-6">
          <div className="flex justify-between items-center h-14">
            <Link href="/" className="flex items-center gap-2.5 group">
              <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" className="group-hover:scale-105 transition-transform">
                <rect width="32" height="32" rx="6" fill="#18181B"/>
                <path d="M8 12L16 8L24 12V20L16 24L8 20V12Z" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                <path d="M16 8V16M16 16L8 20M16 16L24 20" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
              <span className="font-black text-lg">RemoteTaxHub</span>
            </Link>
            <div className="flex items-center gap-6">
              <Link href="/compare" className="text-sm px-4 py-1.5 bg-zinc-900 text-white rounded font-medium hover:bg-zinc-800 transition-colors">
                {t.compare}
              </Link>
              <LanguageSwitcher currentLang={currentLang} onLanguageChange={handleLanguageChange} />
            </div>
          </div>
        </div>
      </nav>

      {/* Header */}
      <div className="pt-24 pb-12 px-6 bg-zinc-50 border-b border-zinc-200">
        <div className="max-w-6xl mx-auto">
          <Link href="/" className="inline-flex items-center gap-1 text-sm text-zinc-600 hover:text-zinc-900 mb-6">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            {t.back}
          </Link>
          <h1 className="text-4xl font-bold text-zinc-900 mb-3">{country.name}</h1>
          <p className="text-lg text-zinc-600">{country.description}</p>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-6 py-12">
        {/* Salary Input */}
        <div className="bg-white border border-zinc-200 rounded-xl p-8 mb-8">
          <h2 className="text-2xl font-bold mb-8 text-zinc-900">{t.yourTakeHomePay}</h2>
          
          <div className="mb-8">
            <label className="block text-sm font-semibold text-zinc-900 mb-4">
              {t.annualSalary} ({country.currency_symbol})
            </label>
            <input
              type="range"
              min="10000"
              max="200000"
              step="5000"
              value={salary}
              onChange={(e) => setSalary(Number(e.target.value))}
              className="w-full h-2 bg-zinc-200 rounded-lg appearance-none cursor-pointer accent-zinc-900"
            />
            <div className="flex justify-between mt-4">
              <span className="text-sm text-zinc-500">{country.currency_symbol}10,000</span>
              <span className="text-3xl font-bold text-zinc-900">
                {country.currency_symbol}{salary.toLocaleString()}
              </span>
              <span className="text-sm text-zinc-500">{country.currency_symbol}200,000</span>
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-4">
            <input
              type="number"
              value={salary}
              onChange={(e) => setSalary(Number(e.target.value))}
              className="border border-zinc-300 rounded-lg px-4 py-3 text-lg focus:border-zinc-900 focus:ring-1 focus:ring-zinc-900 outline-none"
              placeholder={t.customAmount}
            />
            <button
              onClick={downloadPDF}
              className="bg-zinc-900 text-white px-6 py-3 rounded-lg font-semibold hover:bg-zinc-800 transition-colors flex items-center justify-center gap-2"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              {t.downloadPDF}
            </button>
          </div>
        </div>

        {/* Results Grid */}
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          <div className="bg-zinc-50 border border-zinc-200 rounded-xl p-6">
            <div className="text-sm text-zinc-600 mb-2 font-medium">{t.grossSalary}</div>
            <div className="text-4xl font-bold text-zinc-900 mb-1">
              {country.currency_symbol}{calculation.grossSalary.toLocaleString()}
            </div>
            <div className="text-sm text-zinc-500">{t.annualIncome}</div>
          </div>
          
          <div className="bg-red-50 border border-red-200 rounded-xl p-6">
            <div className="text-sm text-red-700 mb-2 font-medium">{t.totalTax}</div>
            <div className="text-4xl font-bold text-red-600 mb-1">
              -{country.currency_symbol}{calculation.totalTax.toLocaleString()}
            </div>
            <div className="text-sm text-red-600">
              {calculation.effectiveTaxRate}% {t.effectiveRate}
            </div>
          </div>
          
          <div className="bg-green-50 border border-green-200 rounded-xl p-6">
            <div className="text-sm text-green-700 mb-2 font-medium">{t.netSalary}</div>
            <div className="text-4xl font-bold text-green-600 mb-1">
              {country.currency_symbol}{calculation.netSalary.toLocaleString()}
            </div>
            <div className="text-sm text-green-600">
              {country.currency_symbol}{calculation.monthlyNet.toLocaleString()}{t.perMonth}
            </div>
          </div>
        </div>

        {/* Tax Breakdown */}
        <div className="grid md:grid-cols-2 gap-8 mb-8">
          <div className="bg-white border border-zinc-200 rounded-xl p-6">
            <h3 className="text-xl font-bold mb-6 text-zinc-900">{t.taxBreakdown}</h3>
            <div className="space-y-4 mb-6">
              <div className="flex justify-between items-center pb-3 border-b border-zinc-100">
                <span className="text-zinc-600">{t.incomeTax}</span>
                <span className="font-semibold text-zinc-900">
                  {country.currency_symbol}{calculation.incomeTax.toLocaleString()}
                </span>
              </div>
              <div className="flex justify-between items-center pb-3 border-b border-zinc-100">
                <span className="text-zinc-600">{t.socialSecurity}</span>
                <span className="font-semibold text-zinc-900">
                  {country.currency_symbol}{calculation.socialSecurity.toLocaleString()}
                </span>
              </div>
              <div className="flex justify-between items-center pt-2">
                <span className="font-semibold text-zinc-900">{t.totalDeductions}</span>
                <span className="font-bold text-zinc-900">
                  {country.currency_symbol}{calculation.totalTax.toLocaleString()}
                </span>
              </div>
            </div>
            
            <div className="h-64">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={pieData}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    label={({ name, percent }) => `${name} ${((percent || 0) * 100).toFixed(0)}%`}
                    outerRadius={80}
                    fill="#8884d8"
                    dataKey="value"
                  >
                    {pieData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip formatter={(value) => `${country.currency_symbol}${Number(value || 0).toLocaleString()}`} />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="bg-white border border-zinc-200 rounded-xl p-6">
            <h3 className="text-xl font-bold mb-6 text-zinc-900">{t.monthlyBudget}</h3>
            <div className="space-y-4 mb-6">
              <div className="flex justify-between items-center pb-3 border-b border-zinc-100">
                <span className="text-zinc-600">{t.monthlyNetIncome}</span>
                <span className="font-semibold text-zinc-900">
                  {country.currency_symbol}{calculation.monthlyNet.toLocaleString()}
                </span>
              </div>
              <div className="flex justify-between items-center pb-3 border-b border-zinc-100">
                <span className="text-zinc-600">{t.costOfLiving}</span>
                <span className="font-semibold text-zinc-900">
                  {country.currency_symbol}{calculation.monthlyCostOfLiving.toLocaleString()}
                </span>
              </div>
              <div className="flex justify-between items-center pt-2">
                <span className="font-semibold text-zinc-900">{t.disposableIncome}</span>
                <span className={`font-bold ${calculation.monthlyDisposable > 0 ? 'text-green-600' : 'text-red-600'}`}>
                  {country.currency_symbol}{calculation.monthlyDisposable.toLocaleString()}
                </span>
              </div>
            </div>

            <div className="h-64">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={monthlyData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                  <XAxis dataKey="name" tick={{ fontSize: 12 }} />
                  <YAxis tick={{ fontSize: 12 }} />
                  <Tooltip formatter={(value) => `${country.currency_symbol}${Number(value || 0).toLocaleString()}`} />
                  <Bar dataKey="value" fill="#18181B" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>

        {/* Tax Brackets Table */}
        <div className="bg-white border border-zinc-200 rounded-xl p-6 mb-8">
          <h3 className="text-xl font-bold mb-6 text-zinc-900">{t.taxBracketsIn} {country.name}</h3>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-zinc-200">
                  <th className="text-left py-3 px-4 text-sm font-semibold text-zinc-900">{t.incomeRange}</th>
                  <th className="text-right py-3 px-4 text-sm font-semibold text-zinc-900">{t.taxRate}</th>
                </tr>
              </thead>
              <tbody>
                {country.tax_brackets.map((bracket, index) => (
                  <tr key={index} className="border-b border-zinc-100 hover:bg-zinc-50">
                    <td className="py-3 px-4 text-sm text-zinc-600">
                      {country.currency_symbol}{bracket.min.toLocaleString()} - {' '}
                      {bracket.max === 999999999 
                        ? '∞' 
                        : `${country.currency_symbol}${bracket.max.toLocaleString()}`}
                    </td>
                    <td className="text-right py-3 px-4 font-semibold text-zinc-900 text-sm">
                      {bracket.rate}%
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="mt-4 text-sm text-zinc-600">
            {t.socialSecurityRate}: <span className="font-semibold text-zinc-900">{country.social_security}%</span>
          </div>
        </div>

        {/* Compare CTA */}
        <div className="bg-zinc-900 text-white rounded-xl p-10 text-center">
          <h2 className="text-2xl font-bold mb-3">
            {t.wantToCompare}
          </h2>
          <p className="text-zinc-400 mb-6">
            {t.seeHowStacks.replace('{country}', country.name)}
          </p>
          <Link
            href="/compare"
            className="inline-block px-6 py-3 bg-white text-zinc-900 font-semibold rounded-lg hover:bg-zinc-100 transition-colors"
          >
            {t.compareCountries}
          </Link>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-zinc-50 border-t border-zinc-200 py-12 mt-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-sm text-zinc-600">
          <p>{t.taxCalculationsDisclaimer}</p>
        </div>
      </footer>
    </div>
  );
}
